"""Build the Microbial Genomics submission package from the SUBMISSION_v4 master (idempotent).

Sources (never edited here): ../01_Manuscript.md, ../02_Figure_legends.md, ../Figures/,
../Supplementary_tables/Table_S1-S3_*.xlsx.

Outputs in this folder:
  01_Manuscript_MicrobialGenomics.md / .docx   single Word file: text + Tables 1-2 + Figures 1-5 with legends,
                                               continuous line numbers, page numbers, A4
  Supplementary_Material_1_Figures_S1-S5.pdf   one PDF: contents page, each Fig S page (vector) followed by its legend
  Supplementary_Material_2_Tables_S1-S3.xlsx   one workbook: Contents sheet + every sheet of S1, S2, S3
  Figures/Fig1-5.pdf                           separate figure files (required at revision)

Guideline basis: Microbiology Society "How to prepare an article" (archived 2026-02-11) and
"Open Data" (archived 2026-06-18); see ../MICGEN_GUIDELINE_CHECK_260923.md.

Run: /home/soon/miniconda3/bin/python build_micgen_package.py
"""
import copy
import re
import shutil
import subprocess
from pathlib import Path

import openpyxl
from docx import Document
from docx.enum.text import WD_BREAK
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Cm, Pt

HERE = Path(__file__).resolve().parent
V4 = HERE.parent
BUILD = HERE / "_build"
PANDOC = "/home/soon/miniconda3/bin/pandoc"
AVR = "AUTHOR VERIFICATION REQUIRED"


def sub1(pattern, repl, text, flags=0):
    """re.sub that must match exactly once (guards against silent no-ops)."""
    new, n = re.subn(pattern, repl, text, count=1, flags=flags)
    assert n == 1, f"pattern not found: {pattern[:60]}"
    return new


def section(text, heading):
    """Return the body of '## heading' up to the next '## '."""
    m = re.search(rf"^## {re.escape(heading)}\n(.*?)(?=^## )", text, re.S | re.M)
    assert m, heading
    return m.group(1).strip()


# ------------------------------------------------------------------ 1 manuscript text
man = (V4 / "01_Manuscript.md").read_text()
leg = (V4 / "02_Figure_legends.md").read_text()

# drafting banner -> MGen banner (HTML comment: not rendered in the .docx)
lines = man.split("\n")
s = next(i for i, l in enumerate(lines) if l.startswith("## 1. Introduction"))
e = next(i for i, l in enumerate(lines) if l.startswith("## CRediT"))
body_words = len(" ".join(lines[s:e]).split())
man = sub1(r"<!--.*?-->",
           "<!--\n**Target journal:** *Microbial Genomics* (Microbiology Society), Research Article\n"
           f"**Word count (body Intro→Conclusions):** {body_words:,}\n"
           "**Source:** ../01_Manuscript.md rebuilt by MicrobialGenomics/build_micgen_package.py\n-->",
           man, re.S)

# Highlights are an Elsevier item
man = sub1(r"\*\*Highlights\*\*\n.*?\n---\n", "", man, re.S)

# American spelling (the category label 'Oxidative-stress defence' is shared with Fig. 4 and the workbooks; left as is)
man = sub1(r"\blabelled\b", "labeled", man)

# figure callouts: the figures and legends use capital panel letters (A), (B); match them
def up(m):
    return m.group(1) + m.group(2).upper()
man, n_call = re.subn(r"(Fig\.\s+S?\d+)([a-e](?:\s*[,–-]\s*[a-e])*)\b", up, man)
assert n_call >= 20, n_call

# Impact Statement + Data Summary after the keywords (Society order: Abstract, Data Summary, Impact Statement, Introduction)
impact = (
    "Microbially induced carbonate precipitation (MICP) is being developed for low-carbon soil stabilization and "
    "biocement production, yet applications still rely on a small set of ureolytic bacteria, chiefly *Sporosarcina "
    "pasteurii*. Nitrogen-rich agricultural environments such as cattle manure are a plausible source of alternative "
    "candidates. By re-analyzing 111 publicly available metagenome-assembled genomes from cattle manure–soil "
    "enrichment cultures, this study prioritizes six genomes from two phylogenetically distinct lineages, "
    "*Sphingobacterium* and *Pseudomonas*\\_E, that encode complete urease and carbonic anhydrase gene sets with "
    "conserved UreC catalytic residues, and identifies two candidate novel *Sphingobacterium* species. The work "
    "provides a reproducible genome-guided prioritization workflow and a short list of testable hypotheses for "
    "isolation and biochemical validation. Because the genomes derive from selective enrichment cultures and no MICP "
    "activity was measured, the candidates are genomic hypotheses rather than validated biocement strains."
)
data_summary = (
    "The authors confirm all supporting data, code and protocols have been provided within the article or through "
    "supplementary data files.\n\n"
    "1. The 111 metagenome-assembled genomes analyzed in this study were generated by Pérez-Valera and Elhottová "  # no citation before the Introduction: numbering starts there
    
    "and are available from NCBI BioProject PRJNA1231077 (https://www.ncbi.nlm.nih.gov/bioproject/PRJNA1231077) and "
    "Zenodo (https://doi.org/10.5281/zenodo.15309541). The SRA run and BioSample accessions of the reads underlying "
    "each genome are listed in Table S2P.\n\n"
    "2. Derived data generated in this study, including the Bakta, Panaroo, GTDB-Tk and DRAM outputs, the full DRAM "
    "metabolism summary, the IQ-TREE report of the SH and AU topology tests and the trait-module tables, are "
    f"available from Zenodo (https://doi.org/{AVR}: reserve the DOI before submission; the record may stay "
    "restricted during peer review and must be public at acceptance).\n\n"
    "3. The analysis scripts are available at https://github.com/Soonlab/Upcycling and are archived in the same "
    "Zenodo record.\n\n"
    "4. Supplementary Material 1 (Figures S1–S5, PDF) and Supplementary Material 2 (Tables S1–S3, Excel workbook) "
    "accompany this article."
)
man = sub1(r"(\*\*Keywords:\*\*[^\n]*\n)",
           r"\1\n## Data Summary\n\n" + data_summary.replace("\\", "\\\\") +
           "\n\n## Impact Statement\n\n" + impact.replace("\\", "\\\\") + "\n", man)

# back matter in Society order and wording
credit = section(man, "CRediT author statement")
genai = section(man, "Declaration of generative AI and AI-assisted technologies in the writing process")
ethics = section(man, "Ethics and biosafety statement")
funding = section(man, "Funding")
old_block = re.search(r"^## CRediT author statement\n.*?(?=^## References)", man, re.S | re.M)
assert old_block
new_back = (
    "## Conflicts of interest\n"
    "The author(s) declare that there are no conflicts of interest.\n\n"
    "## Funding information\n"
    f"{funding} {AVR}: confirm the following sentence. The funder had no role in study design, data analysis, "
    "decision to publish, or preparation of the manuscript.\n\n"
    "## Ethical approval and biosafety\n"
    f"{ethics}\n\n"
    "## Author contributions\n"
    f"{credit}\n\n"
    "## Acknowledgements\n"
    "The genomes analyzed in this study were generated and made publicly available by Pérez-Valera and Elhottová "
    f"(2025). {AVR}: add any further acknowledgements, including language-editing services if used.\n\n"
    "## Declaration of generative AI and AI-assisted technologies in the writing process\n"
    f"{genai}\n\n"
)
man = man[:old_block.start()] + new_back + man[old_block.end():]
assert "## Data and code availability" not in man

# ------------------------------------------------------------------ 1b references: Harvard author-date -> Vancouver numbered
# Microbial Genomics house style (checked against a 2026 MGen article, PMC13580827): numbers in square brackets in
# order of first citation, "[3, 17]", ranges only for >= 3 consecutive numbers "[4-8]"; list "1. Surname AB, ... Title.
# Journal Year;Vol:Pages. DOI". Full journal names are kept (the journal applies its own abbreviations at production).
NAME = r"[A-Z][A-Za-zÀ-ɏ'\-]+(?: [A-Z][A-Za-zÀ-ɏ'\-]+)*"
CITE = re.compile(rf"^({NAME}|van [A-Z][\w'\-]+)(?: and ({NAME}))?(?: et al\.)?, ((?:19|20)\d\d)[a-z]?$")
HARV = re.compile(r"^(?P<auth>.+?), (?P<year>\d{4})[a-z]?\. (?P<title>.+?[.?!]) \*(?P<jour>[^*]+)\* "
                  r"(?P<vol>\d+)(?P<iss>\(\d+\))?, (?P<pages>[A-Za-z]*\d+(?:–[A-Za-z]*\d+)?)\.(?: (?P<doi>https://doi\.org/\S+))?$")


def vanc_authors(auth):
    etal = auth.endswith(", et al.")
    auth = auth[:-len(", et al.")] if etal else auth
    names = re.findall(r"([^,]+), ((?:[A-Z][a-z]?\.-?)+)(?:, |$)", auth)
    rebuilt = ", ".join(f"{a}, {b}" for a, b in names)
    assert rebuilt == auth, (auth, rebuilt)
    out = ", ".join(f"{a.strip()} {b.replace('.', '').replace('-', '')}" for a, b in names)
    return out + (", et al." if etal else ".")


def to_vancouver(text):
    head, rest = text.split("## References\n", 1)
    reflist, tail = rest.split("\n\n## Table 1 |", 1)
    tail = "\n\n## Table 1 |" + tail
    entries = [l for l in reflist.split("\n") if l.strip() and l.strip() != "---"]
    keyed = {}
    for e in entries:
        first = e.split(", ")[0]
        year = re.search(r", (\d{4})[a-z]?\. ", e).group(1)
        second = re.match(r"[^,]+, [A-Z.\-]+, ([^,]+), ", e)
        assert (first, year) not in keyed, (first, year)
        keyed[(first, year)] = (e, second.group(1) if second else None)
    order = []

    def num(item):
        m = CITE.match(item.strip())
        if not m:
            return None
        key = (m.group(1), m.group(3))
        assert key in keyed, f"citation without entry: {item}"
        if m.group(2):
            assert keyed[key][1] == m.group(2), f"second author mismatch: {item}"
        if key not in order:
            order.append(key)
        return order.index(key) + 1

    def fmt(nums):
        nums = sorted(set(nums))
        out, i = [], 0
        while i < len(nums):
            j = i
            while j + 1 < len(nums) and nums[j + 1] == nums[j] + 1:
                j += 1
            out.append(f"{nums[i]}–{nums[j]}" if j - i >= 2 else ", ".join(map(str, nums[i:j + 1])))
            i = j + 1
        return "[" + ", ".join(out) + "]"

    def paren(m):
        items = [x.strip() for x in m.group(1).split(";")]
        nums, keep = [], []
        for it in items:
            n = num(it)
            (nums.append(n) if n else keep.append(it))
        if not nums:
            return m.group(0)
        return (f"({'; '.join(keep)}) " if keep else "") + fmt(nums)

    def narrative(m):
        return f"{m.group(1)} {fmt([num(m.group(1) + ', ' + m.group(2))])}"

    # walk the text in document order so that numbering follows first appearance
    pieces, pos = [], 0
    rx = re.compile(rf"\(([^()]*?, (?:19|20)\d\d[a-z]?(?=[;)])[^()]*)\)|({NAME}(?: and {NAME}| et al\.)?) \(((?:19|20)\d\d)[a-z]?\)")
    for m in rx.finditer(head):
        pieces.append(head[pos:m.start()])
        if m.group(1) is not None:
            pieces.append(paren(m))
        else:
            n = num(f"{m.group(2)}, {m.group(3)}")
            pieces.append(f"{m.group(2)} {fmt([n])}" if n else m.group(0))
        pos = m.end()
    pieces.append(head[pos:])
    head = "".join(pieces)
    leftover = re.findall(r"\([^()]*\b(?:19|20)\d\d[a-z]?\)", head)
    assert not [x for x in leftover if CITE.match(x.strip("()").split(";")[-1].strip())], leftover
    assert len(order) == len(entries), f"{len(entries) - len(order)} entries never cited"

    lines = []
    for i, key in enumerate(order, 1):
        e = keyed[key][0]
        m = HARV.match(e)
        if m:
            iss = m.group("iss") or ""
            line = (f"{i}. {vanc_authors(m.group('auth'))} {m.group('title')} {m.group('jour')} "
                    f"{m.group('year')};{m.group('vol')}{iss}:{m.group('pages')}.")
            if m.group("doi"):
                line += f" {m.group('doi')}"
        else:  # software / web resource
            sm = re.match(r"^(?P<auth>.+?), (?P<year>\d{4})[a-z]?\. (?P<rest>.+) (?P<url>https?://\S+)$", e)
            assert sm, e
            line = (f"{i}. {vanc_authors(sm.group('auth'))} {sm.group('rest')} {sm.group('url')} "
                    f"({sm.group('year')}; accessed {AVR})")
        lines.append(line)
    return head + "## References\n\n" + "\n\n".join(lines) + "\n\n---" + tail, len(order)


man, n_refs = to_vancouver(man)
# the banner states the body word count after conversion (numbered citations are shorter)
_l = man.split("\n")
_s = next(i for i, l in enumerate(_l) if l.startswith("## 1. Introduction"))
_e = next(i for i, l in enumerate(_l) if l.startswith("## Conflicts of interest"))
body_words = len(" ".join(_l[_s:_e]).split())
man = sub1(r"(\*\*Word count \(body Intro→Conclusions\):\*\* )[\d,]+", rf"\g<1>{body_words:,}", man)

# ------------------------------------------------------------------ 2 figures + legends appended to the manuscript
BUILD.mkdir(exist_ok=True)
fig_block = ["## Figures\n"]  # page breaks are set on the paragraphs in style_doc (no empty break paragraphs)
for i in range(1, 6):
    png = BUILD / f"Fig{i}.png"
    subprocess.run(["pdftoppm", "-png", "-r", "300", "-singlefile", str(V4 / "Figures" / f"Fig{i}.pdf"),
                    str(png.with_suffix(""))], check=True)
    m = re.search(rf"^### (Figure {i} \|.*?)\n(.*?)(?=^### |^## )", leg, re.S | re.M)
    assert m, i
    title, body = m.group(1).strip(), m.group(2).strip()
    fig_block.append(f"![]({png}){{width=17cm}}\n\n**{title}** {body}\n")
# tables stay where the master has them (after References); figures go after the tables
man = man.rstrip() + "\n" + "\n".join(fig_block)
man = sub1(r"\n---\n\n## Table 1 \|", "\n\n## Table 1 |", man)
# the date line is not a manuscript item
man = sub1(r'^date: "2026"\n', "", man, re.M)

out_md = HERE / "01_Manuscript_MicrobialGenomics.md"
out_md.write_text(man)

# ------------------------------------------------------------------ 3 docx: pandoc, then A4 / Arial / line + page numbers
out_docx = HERE / "01_Manuscript_MicrobialGenomics.docx"
subprocess.run([PANDOC, str(out_md), "-o", str(out_docx),
                "--from=markdown+pipe_tables+tex_math_dollars+raw_attribute"], check=True)


def style_doc(path, line_numbers):
    doc = Document(path)
    for st in doc.styles:
        if st.type == 1 and st.font is not None:  # paragraph styles
            st.font.name = "Arial"
            rpr = st.element.get_or_add_rPr()
            fonts = rpr.find(qn("w:rFonts"))
            if fonts is None:
                fonts = OxmlElement("w:rFonts")
                rpr.append(fonts)
            for a in ("w:ascii", "w:hAnsi", "w:cs", "w:eastAsia"):
                fonts.set(qn(a), "Arial")
            for a in ("w:asciiTheme", "w:hAnsiTheme", "w:cstheme", "w:eastAsiaTheme"):
                if fonts.get(qn(a)) is not None:
                    del fonts.attrib[qn(a)]
    for name, size in (("Title", 16), ("Normal", 11), ("Body Text", 11), ("First Paragraph", 11), ("Compact", 8)):
        if name in [s.name for s in doc.styles]:
            doc.styles[name].font.size = Pt(size)
    for sec in doc.sections:
        sec.page_width, sec.page_height = Cm(21.0), Cm(29.7)
        sec.left_margin = sec.right_margin = Cm(2.0)
        sec.top_margin = sec.bottom_margin = Cm(2.0)
        sp = sec._sectPr
        if line_numbers and sp.find(qn("w:lnNumType")) is None:
            ln = OxmlElement("w:lnNumType")
            ln.set(qn("w:countBy"), "1")
            ln.set(qn("w:restart"), "continuous")
            ln.set(qn("w:distance"), "284")
            # lnNumType must precede pgNumType/cols/etc.; insert after pgMar when present
            pgmar = sp.find(qn("w:pgMar"))
            (pgmar.addnext(ln) if pgmar is not None else sp.append(ln))
        # centered page number in the footer
        p = sec.footer.paragraphs[0]
        if line_numbers and not p.runs:
            p.alignment = 1
            r = p.add_run()
            for tag, attr in (("w:fldChar", {"w:fldCharType": "begin"}), ("w:instrText", None),
                              ("w:fldChar", {"w:fldCharType": "end"})):
                el = OxmlElement(tag)
                if attr:
                    for k, v in attr.items():
                        el.set(qn(k), v)
                else:
                    el.set(qn("xml:space"), "preserve")
                    el.text = " PAGE "
                r._r.append(el)
    if line_numbers:  # new page before Tables, Figures and every figure image
        for para in doc.paragraphs:
            t = para.text.strip()
            if (para.style.name.startswith("Heading") and (t.startswith("Table 1 |") or t == "Figures")) \
                    or para._p.xpath(".//w:drawing"):
                if t != "" or para._p.xpath(".//w:drawing"):
                    para.paragraph_format.page_break_before = True
        # the first figure follows the 'Figures' heading directly
        heads = [q for q in doc.paragraphs if q.text.strip() == "Figures"]
        if heads:
            nxt = heads[0]._p.getnext()
            from docx.text.paragraph import Paragraph
            Paragraph(nxt, heads[0]._parent).paragraph_format.page_break_before = False
    doc.save(path)


style_doc(out_docx, line_numbers=True)

# ------------------------------------------------------------------ 4 separate main figure files (revision stage)
(HERE / "Figures").mkdir(exist_ok=True)
for i in range(1, 6):
    shutil.copy2(V4 / "Figures" / f"Fig{i}.pdf", HERE / "Figures" / f"Fig{i}.pdf")

# ------------------------------------------------------------------ 5 Supplementary Material 1: one PDF
title = re.search(r'title: "(.*?)"', man).group(1)
title_plain = title.replace("*", "")
sm1 = [f"# Supplementary Material 1\n\n**{title}**\n\nContents: Figures S1–S5, each followed by its legend. "
       "Tables S1–S3 are provided as Supplementary Material 2 (Excel workbook); their descriptions are listed below.\n"]
for k in (1, 2, 3):
    m = re.search(rf"^### (Table S{k} \|.*?)\n(.*?)(?=^### |^## |\Z)", leg, re.S | re.M)
    sm1.append(f"**{m.group(1).strip()}** {m.group(2).strip()}\n")
parts_md = [("00_contents", "\n".join(sm1))]
for i in range(1, 6):
    m = re.search(rf"^### (Figure S{i} \|.*?)\n(.*?)(?=^### |^## )", leg, re.S | re.M)
    assert m, i
    parts_md.append((f"S{i}_legend", f"**{m.group(1).strip()}** {m.group(2).strip()}\n"))
pdfs = []
for stem, text in parts_md:
    md = BUILD / f"sm1_{stem}.md"
    md.write_text(text)
    dx = md.with_suffix(".docx")
    subprocess.run([PANDOC, str(md), "-o", str(dx)], check=True)
    style_doc(dx, line_numbers=False)
    subprocess.run(["soffice", "--headless", "--convert-to", "pdf", "--outdir", str(BUILD), str(dx)],
                   check=True, capture_output=True)
    pdfs.append(dx.with_suffix(".pdf"))
order = [pdfs[0]]
for i in range(1, 6):
    order += [V4 / "Figures" / f"Fig_S{i}.pdf", pdfs[i]]
sm1_pdf = HERE / "Supplementary_Material_1_Figures_S1-S5.pdf"
subprocess.run(["pdfunite", *map(str, order), str(sm1_pdf)], check=True)

# ------------------------------------------------------------------ 6 Supplementary Material 2: one workbook
out = openpyxl.Workbook()
cs = out.active
cs.title = "Contents"
cs.append(["Supplementary Material 2"])
cs.append([title_plain])
cs.append([])
cs.append(["Workbook", "Description", "Sheets"])
srcs = sorted((V4 / "Supplementary_tables").glob("Table_S[123]_*.xlsx"))
assert len(srcs) == 3, srcs
for f in srcs:
    k = re.search(r"Table_S(\d)", f.name).group(1)
    m = re.search(rf"^### (Table S{k} \|.*?)\n(.*?)(?=^### |^## |\Z)", leg, re.S | re.M)
    wb = openpyxl.load_workbook(f)
    names = []
    for ws in wb.worksheets:
        name = f"S{k}_README" if ws.title == "README" else ws.title
        assert name not in out.sheetnames, name
        names.append(name)
        nw = out.create_sheet(name)
        for row in ws.iter_rows():
            for c in row:
                n = nw.cell(row=c.row, column=c.column, value=c.value)
                if c.has_style:
                    n.font, n.fill, n.border = copy.copy(c.font), copy.copy(c.fill), copy.copy(c.border)
                    n.alignment, n.number_format = copy.copy(c.alignment), c.number_format
        for col, dim in ws.column_dimensions.items():
            nw.column_dimensions[col].width = dim.width
        for rng in ws.merged_cells.ranges:
            nw.merge_cells(str(rng))
        nw.freeze_panes = ws.freeze_panes
    cs.append([m.group(1).strip().replace("*", ""), m.group(2).strip().replace("*", ""), ", ".join(names)])
cs.column_dimensions["A"].width = 45
cs.column_dimensions["B"].width = 100
cs.column_dimensions["C"].width = 60
out.save(HERE / "Supplementary_Material_2_Tables_S1-S3.xlsx")

# ------------------------------------------------------------------ 7 cover letter
cl = (HERE / "03_Cover_letter_MicrobialGenomics.md")
subprocess.run([PANDOC, str(cl), "-o", str(cl.with_suffix(".docx"))], check=True)
style_doc(cl.with_suffix(".docx"), line_numbers=False)

print(f"body words {body_words}; callouts upper-cased {n_call}; references numbered {n_refs}")
print("built:", out_md.name, out_docx.name, sm1_pdf.name, "Supplementary_Material_2_Tables_S1-S3.xlsx", "Figures/", cl.name)
