#!/usr/bin/env python
"""SUBMISSION_v4 reframing (2026-09-23): the 111 MAGs are the public dataset of
Pérez-Valera and Elhottová (2025) - enrichment-culture MAGs from dairy-cattle manure,
manured soil and soil microcosms - and the MAG prefixes C/M/S/V are binning tools, not
cattle/swine/sheep/poultry.  This script rewrites the SUBMISSION_v2 master accordingly:

  * title, highlights (<= 85 characters, MicRes), abstract, keywords (6), introduction
  * Methods 2.1 (data source, enrichment, assembly), 2.6, 2.9 (MGnify and the contig-coverage
    proxy removed; read-mapping coverage from the deposited metadata instead)
  * Results 3.1, 3.5, 3.9, 3.10 (every "waste source" analysis removed; MGnify removed)
  * Discussion 4.1, 4.3, 4.4 (enrichment-culture limitation added), Conclusions, Ethics,
    Data availability; Table 1 gains a sample-origin column
  * figure / table legends (Fig 1, Fig 5, Fig S2, Fig S5, Tables 1, S2, S3)
  * table callouts re-lettered for the v4 workbooks (S3E,F -> S3D,E; S3J,K,M -> S3G,H,I)

Input: ../SUBMISSION_v2/01_Manuscript.md and 02_Figure_legends.md (read-only).
Output: ./01_Manuscript.md, ./02_Figure_legends.md.  Every replacement must match exactly
once (or the stated count); the reference list is regenerated afterwards by
references/04_apply_to_master.py.  Idempotent: always rebuilds from v2.
"""
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
V2 = HERE.parent / "SUBMISSION_v2"
man = (V2 / "01_Manuscript.md").read_text(encoding="utf-8")
leg = (V2 / "02_Figure_legends.md").read_text(encoding="utf-8")
DATA = "Pérez-Valera and Elhottová, 2025"


def rep(text, old, new, count=1):
    n = text.count(old)
    assert n == count, f"expected {count}x, found {n}x: {old[:80]!r}"
    return text.replace(old, new)


def rep_section(text, start_heading, end_heading, new_block):
    """Replace everything from start_heading (inclusive) up to end_heading (exclusive)."""
    s = text.index(start_heading)
    e = text.index(end_heading, s)
    return text[:s] + new_block + text[e:]


# ================================================================ front matter
man = rep(man, 'title: "Comparative genomics of livestock-waste MAGs identifies convergent *Sphingobacterium* and *Pseudomonas* lineages with genomic potential for microbially induced carbonate precipitation"',
          'title: "Comparative genomics of enrichment-culture MAGs from cattle manure–soil microcosms identifies convergent *Sphingobacterium* and *Pseudomonas* lineages with genomic potential for microbially induced carbonate precipitation"')
man = rep(man, "**Source:** Manuscript_revised.docx (authors' revision, saved 2026-09-17), ported by port_revised_260923.py; the reference list is regenerated by references/04_apply_to_master.py.",
          "**Source:** SUBMISSION_v2 master (authors' revision of 2026-09-17) reframed by reframe_260923.py for the true data provenance (Pérez-Valera and Elhottová, 2025; see data_provenance_260923/); the reference list is regenerated by references/04_apply_to_master.py.")

HIGHLIGHTS = [
    "111 cattle manure–soil microcosm MAGs yield six MICP candidates in two lineages",
    "Core urease loci show little evidence of recent mobilization",
    "UreC catalytic residues and predicted fold are conserved in all six candidates",
    "Candidates are enriched for alkaline-stress, oxidative and CAZyme-related traits",
    "S13 and S16 are candidate novel *Sphingobacterium* species for validation",
]
for h in HIGHLIGHTS:
    assert len(h.replace("*", "")) <= 85, (len(h), h)
old_hl = man[man.index("**Highlights**"):man.index("---\n\n## Abstract")]
man = man.replace(old_hl, "**Highlights**\n\n" + "\n\n".join(f"- {h}" for h in HIGHLIGHTS) + "\n\n")

ABSTRACT = ("Microbially induced carbonate precipitation (MICP) is a promising low-carbon ground-improvement strategy, but applications rely on a narrow set of ureolytic microorganisms that may be poorly suited to nutrient-rich, chemically variable waste environments. We re-analyzed 111 publicly available metagenome-assembled genomes (MAGs) recovered from selective enrichment cultures of dairy-cattle manure, manure-amended soil, and soil microcosms to identify genomic candidates for MICP in manure-associated settings. Twenty-seven MAGs encoded a complete *ureA–G* gene set plus carbonic anhydrase (*cah*); six—four *Sphingobacterium* and two *Pseudomonas*\\_E—were prioritized as phylogenetically distinct, functionally convergent lineages. In better-assembled genomes, *ureABCDEFG* occurred on a single contig, with little evidence of recent mobilization of core urease loci. The candidates encoded traits linked to alkaline stress, oxidative defense, compatible-solute biosynthesis, and polysaccharide utilization. All six retained the seven canonical UreC catalytic residues, and ESMFold models showed the expected (β/α)₈ TIM-barrel architecture (TM-scores, 0.597–0.678). S13 and S16 represented putative novel *Sphingobacterium* species. Urease genes were under strong purifying selection (codeml M0 ω ≤ 0.09), whereas *ureG* showed relatively relaxed constraint. No acquired antimicrobial-resistance genes or plasmid replicons were detected. Because the MAGs derive from selective enrichment cultures, they represent culturable, medium-tolerant taxa rather than the manure community. These findings identify noncanonical MICP candidates from manure-associated microbiomes and support targeted biochemical and experimental validation.")
assert len(ABSTRACT.split()) <= 250, len(ABSTRACT.split())
old_abs = man[man.index("## Abstract\n\n") + len("## Abstract\n\n"):man.index("\n\n**Keywords:**")]
man = man.replace(old_abs, ABSTRACT)
man = rep(man, "**Keywords:** microbially induced carbonate precipitation; metagenome-assembled genomes; *Sphingobacterium*; urease; carbonic anhydrase; alkaline stress; comparative genomics; livestock-waste valorization",
          "**Keywords:** microbially induced carbonate precipitation; metagenome-assembled genomes; *Sphingobacterium*; urease; carbonic anhydrase; cattle manure")

# ================================================================ 1 Introduction
man = rep(man, "Livestock slurry contains urea, ammonia, inorganic ions, volatile fatty acids, and complex organic substrates, making it an environmental challenge and a reservoir of microorganisms adapted to nutrient-rich, chemically variable conditions. Genome-resolved metagenomics enables culture-independent recovery of metagenome-assembled genomes (MAGs) from these environments (Anantharaman et al., 2016; Parks et al., 2017; Chen et al., 2021; Nayfach et al., 2021). Coupled with comparative genomics and metabolic reconstruction, it can identify microorganisms encoding MICP-associated functions and traits relevant to persistence in livestock waste (Tonkin-Hill et al., 2020; Shaffer et al., 2020).",
          "Cattle manure and manure-amended soils contain urea, ammonia, inorganic ions, volatile fatty acids, and complex organic substrates, making them an environmental challenge and a reservoir of microorganisms adapted to nutrient-rich, chemically variable conditions. Genome-resolved metagenomics enables culture-independent recovery of metagenome-assembled genomes (MAGs) from such environments (Anantharaman et al., 2016; Parks et al., 2017; Chen et al., 2021; Nayfach et al., 2021), and public MAG datasets can be re-analyzed to address questions beyond those of the original study. Coupled with comparative genomics and metabolic reconstruction, this approach can identify microorganisms encoding MICP-associated functions and traits relevant to persistence in manure-associated environments (Tonkin-Hill et al., 2020; Shaffer et al., 2020).")
man = rep(man, "Here, we applied a genomics-first strategy to 111 MAGs from four livestock-waste microbiomes to identify",
          f"Here, we applied a genomics-first strategy to a public dataset of 111 MAGs recovered from selective enrichment cultures of dairy-cattle manure, manure-amended soil, and soil microcosms ({DATA}) to identify")

# ================================================================ 2 Methods
man = rep(man, "### 2.1 MAG collection, annotation, and pan-genome analysis\nWe recovered 111 metagenome-assembled genomes (MAGs) from cattle (“C”), swine (“M”), sheep (“S”), and poultry (“V”) waste metagenomes using the ACE hybrid pipeline. MAGs with ≥50% completeness and ≤10% contamination were retained, meeting MIMAG medium-quality standards or better (Bowers et al., 2017). Genome sizes were 1.9–6.2 Mb (median, 3.8 Mb), with GC contents of 32–68%.",
          f"### 2.1 MAG dataset, annotation, and pan-genome analysis\nWe re-analyzed the 111 metagenome-assembled genomes (MAGs) published by the data producers as a public dataset (NCBI BioProject PRJNA1231077; Zenodo, https://doi.org/10.5281/zenodo.15309541; {DATA}). As described there, the MAGs derive from laboratory microcosms combining fresh manure from a dairy farm with pasture soil from two organic farms (České Budějovice, Czech Republic), sampled after 2, 14, and 28 days of incubation; samples were enriched on CHROMagar Acinetobacter (28 °C, 24 h) before DNA extraction and Illumina NovaSeq sequencing, and MAGs were reconstructed with metaSPAdes (individual and co-assemblies), five binning tools (MetaBAT, MaxBin, SemiBin2, COMEbin, and AVAMB), and dereplication at 95% ANI. The related cultivation study of the same microcosms has been published separately (Sardar et al., 2023). MAG identifiers (prefixes C, M, S, and V) denote the binning tool, not the sample of origin; 44 MAGs derive from manure, 38 from manured soil, and 29 from soil (Table S2P). All 111 MAGs met MIMAG medium-quality standards or better (≥50% completeness, ≤10% contamination; Bowers et al., 2017). Because the dataset derives from selective enrichment cultures, it represents culturable, medium-tolerant taxa—99 of the 111 MAGs are Pseudomonadota—rather than the full manure or soil community. Genome sizes were 1.9–6.2 Mb (median, 3.8 Mb), with GC contents of 32–68%.")
man = rep(man, "Each dataset included the prioritized candidates and 12 additional MAGs spanning the four livestock-waste sources, limited to genomes",
          "Each dataset included the prioritized candidates and 12 additional urease-positive MAGs from across the panel, limited to genomes")
old_29 = man[man.index("### 2.9 External prevalence and coverage-based abundance proxy"):man.index("## 3. Results")]
new_29 = ("### 2.9 Within-genus prevalence and read-mapping coverage\n"
          "Within-genus prevalence was assessed in 146 *Pseudomonas*\\_E reference genomes using HMMER3 against urease- and carbonic anhydrase-associated Pfam profiles (E < 1 × 10⁻⁵). "
          "The relative abundance of each MAG in its sample of origin was taken from the read-mapping genome coverage deposited with the dataset (CoverM; Table S2P) and compared between the six prioritized candidates and the remaining MAGs with a two-sided Mann–Whitney U test. "
          "Because coverage depends on sequencing depth, assembly type, and the enrichment step, these values were used only as a coarse abundance proxy, not as estimates of abundance in the original manure or soil.\n\n")
man = man.replace(old_29, new_29)

# ================================================================ 3 Results
man = rep(man, "The 111 MAGs spanned multiple bacterial phyla and genera (Table S2A).",
          "The 111 MAGs comprised 99 Pseudomonadota and 12 Bacteroidota across 17 genera, dominated by *Pseudomonas*\\_E, *Stenotrophomonas*, *Acinetobacter*, and *Achromobacter* (Table S2A), consistent with the selective enrichment used to generate the dataset.")
man = rep(man, "### 3.5 Prioritized candidates are enriched for traits relevant to livestock-slurry environments",
          "### 3.5 Prioritized candidates are enriched for traits relevant to manure-associated environments")
man = rep(man, "consistent with genomic capacity for ionic stress tolerance and complex-substrate utilization in livestock-waste environments.",
          "consistent with genomic capacity for ionic stress tolerance and complex-substrate utilization in manure-associated environments.")
man = rep(man, "### 3.9 MICP-associated genomic features are uncommon in livestock microbiomes and vary across lineages\nScreening 7,599 species clusters from four MGnify livestock-microbiome catalogs identified 233 (3.07%) with *ureABC* plus at least one carbonic anhydrase (Fig. 5b; Table S3G,H). Another 265 clusters (3.49%) contained *ureC* and a carbonic anhydrase-associated domain on the same contig. Only two *Sphingobacterium* clusters were present, neither with the full marker combination, indicating limited representation of this lineage in current livestock-microbiome catalogs.\n\nAmong 146 *Pseudomonas*\\_E reference genomes, UreC and carbonic anhydrase were common individually; 53 genomes (36.3%) encoded both on the same contig (Fig. S4e; Table S3E,F), indicating substantial but nonuniversal local co-occurrence.\n\nLength-weighted assembly coverage was similar between the six prioritized candidates and remaining MAGs (26.8× vs. 25.5×; *P* = 0.27; Fig. S5b,c), with no detectable difference in coverage-based relative abundance. The candidates came from cattle (C22), swine (M1), and sheep (S13, S16, S23, and S26) microbiomes.",
          "### 3.9 Within-genus prevalence, sample origin, and secondary-metabolite profiles of the candidates\nAmong 146 *Pseudomonas*\\_E reference genomes, UreC and carbonic anhydrase were common individually; 53 genomes (36.3%) encoded both on the same contig (Fig. S4e; Table S3D,E), indicating substantial but nonuniversal local co-occurrence.\n\nThe two *Pseudomonas*\\_E candidates (M1 and S26) derived from manure microcosms, whereas the four *Sphingobacterium* candidates (S13, S16, S23, and C22) derived from manured-soil microcosms of the same soil series, sampled on days 2, 14, and 28 (Table S2P). S13 and S16 were recovered from the same day-28 co-assembly but are distinct genomes (AAI, 82.5%; Table S1F). Read-mapping genome coverage in the sample of origin did not differ between the six prioritized candidates and the remaining MAGs (median, 9.5× vs. 17.6×; *P* = 0.12; Fig. S5b; Table S3J), with no detectable difference in coverage-based relative abundance.")
man = rep(man, "whereas RRE-containing RiPP clusters occurred across most candidates (Fig. 5c; Table S3M).",
          "whereas RRE-containing RiPP clusters occurred across most candidates (Fig. 5b; Table S3I).")
man = rep(man, "Jaccard PCoA of Panaroo gene presence/absence showed strong genus-level structure (PERMANOVA pseudo-F = 8.21, *P* = 0.001) but no significant separation by livestock source (pseudo-F = 1.25, *P* = 0.11; Fig. 5d; Table S3C,D), whereas functional-trait profiles differed by source (pseudo-F = 2.71, *P* = 0.001), suggesting that overall gene content was primarily taxonomic while functional traits also reflected waste source.",
          "Jaccard PCoA of Panaroo gene presence/absence showed strong genus-level structure (PERMANOVA pseudo-F = 8.21, *P* = 0.001; Fig. 5c; Table S3C), indicating that overall gene content was primarily taxonomic; the two candidate lineages occupied distinct regions of the ordination.")
man = rep(man, "(Fig. 3c; Table S3J)", "(Fig. 3c; Table S3G)")
man = rep(man, "(0.31 vs. 0.074; *P* = 7.7 × 10⁻⁸; Fig. 3d; Table S3K)", "(0.31 vs. 0.074; *P* = 7.7 × 10⁻⁸; Fig. 3d; Table S3H)")

# ================================================================ 4 Discussion
man = rep(man, "### 4.1 Livestock waste provides a reservoir of noncanonical MICP candidates",
          "### 4.1 Manure-associated microbiomes provide noncanonical MICP candidates")
man = rep(man, "MGnify comparison showed that the MICP-associated marker combination was uncommon in livestock microbiomes: only 3.07% of 7,599 species clusters encoded *ureABC* and at least one carbonic anhydrase. *Sphingobacterium* was rare, with only two clusters, neither carrying the full marker combination. Thus, the four *Sphingobacterium* candidates, including putative novel species S13 and S16, broaden the taxonomic diversity of genomic candidates for ureolytic MICP.",
          "Within *Pseudomonas*\\_E, urease and carbonic anhydrase genes were common, and 36.3% of 146 reference genomes carried both on one contig, so the two *Pseudomonas*\\_E candidates are typical of their genus in marker content. *Sphingobacterium*, by contrast, is not among the taxa conventionally used for MICP, and the four *Sphingobacterium* candidates, including putative novel species S13 and S16, broaden the taxonomic diversity of genomic candidates for ureolytic MICP.")
man = rep(man, "These findings indicate that livestock slurry is a reservoir of useful microbial functions, not merely a waste stream (Gupta et al., 2016). Microorganisms adapted to ammonia, variable ionic conditions, and complex organic substrates may be candidates for waste-compatible MICP, linking genome-guided bioprospecting with livestock-waste valorization and circular-bioeconomy applications.",
          "These findings indicate that cattle manure and manure-amended soil are reservoirs of useful microbial functions, not merely waste streams (Gupta et al., 2016). Microorganisms adapted to ammonia, variable ionic conditions, and complex organic substrates may be candidates for waste-compatible MICP, linking genome-guided bioprospecting with livestock-waste valorization and circular-bioeconomy applications. Because the dataset was generated by selective enrichment, the candidates identified here are, by construction, taxa that grow readily on laboratory media, which is an advantage for subsequent isolation but not evidence of their abundance in manure.")
man = rep(man, "### 4.3 Candidate genomes combine slurry-associated traits with engineering-relevant genomic features\nThe prioritized candidates also encoded traits consistent with persistence in chemically challenging livestock-waste environments,",
          "### 4.3 Candidate genomes combine manure-associated traits with engineering-relevant genomic features\nThe prioritized candidates also encoded traits consistent with persistence in chemically challenging manure-associated environments,")
man = rep(man, "Whether these features reduce reliance on refined nutrients during slurry-based MICP requires experimental validation.",
          "Whether these features reduce reliance on refined nutrients during manure-based MICP requires experimental validation.")
man = rep(man, "Third, assembly fragmentation limits inference of gene organization.",
          "Third, the MAG panel derives from selective enrichment cultures (CHROMagar Acinetobacter) of manure–soil microcosms built from one dairy farm and two soils, and the six candidates originate from two experimental series. The panel therefore represents culturable, medium-tolerant taxa—predominantly Pseudomonadota—rather than the manure or soil community; prevalence within the panel does not describe environmental abundance, the trait enrichment describes the candidates relative to other enrichment-derived genomes, and generalization to other manures requires additional datasets.\n\nFourth, assembly fragmentation limits inference of gene organization.")
man = rep(man, "Livestock-slurry and sand-column assays benchmarked against *S. pasteurii* would then assess application-relevant performance.",
          "Manure-slurry and sand-column assays benchmarked against *S. pasteurii* would then assess application-relevant performance.")
man = rep(man, "Overall, this study broadens the genomic landscape of ureolytic MICP and identifies livestock waste as a source of noncanonical microbial candidates,",
          "Overall, this study broadens the genomic landscape of ureolytic MICP and identifies cattle manure and manure-amended soil as sources of noncanonical microbial candidates,")

# ================================================================ 5 Conclusions
man = rep(man, "Comparative genomics of 111 livestock-waste MAGs identified urease–carbonic anhydrase gene sets",
          "Comparative genomics of 111 enrichment-culture MAGs from cattle manure–soil microcosms identified urease–carbonic anhydrase gene sets")
man = rep(man, "consistent with potential adaptation to livestock-slurry environments. No acquired antimicrobial-resistance genes or plasmid replicons were detected, but these findings require experimental validation. Comparison with 7,599 livestock-microbiome species clusters indicated that the urease–carbonic anhydrase combination is uncommon; S13 and S16 were candidate novel *Sphingobacterium* species.",
          "consistent with potential adaptation to manure-associated environments. No acquired antimicrobial-resistance genes or plasmid replicons were detected, but these findings require experimental validation. S13 and S16 were candidate novel *Sphingobacterium* species.")
man = rep(man, "Together, these findings support livestock waste as a source of noncanonical MICP candidates",
          "Together, these findings support cattle manure and manure-amended soil as sources of noncanonical MICP candidates")

# ================================================================ back matter
man = rep(man, "This study used only bioinformatic analyses of previously generated metagenome-assembled genomes from livestock-waste samples. It involved no human participants, clinical data, or animal experiments. Sample collection in the originating project followed applicable institutional and national guidelines for livestock and environmental sampling.",
          f"This study used only bioinformatic analyses of publicly available metagenome-assembled genomes (NCBI BioProject PRJNA1231077; {DATA}). It involved no human participants, clinical data, or animal experiments. Sample collection and the microcosm experiments were performed by the data producers under their institutional and national guidelines.")
man = rep(man, "All MAGs, Bakta/Panaroo/GTDB-Tk/DRAM outputs, derived trait-module tables and analysis scripts are available at `/data/data/Upcycling/` and will be deposited at NCBI BioProject PRJNA-XXXXXXX and Zenodo (DOI on acceptance).",
          f"The 111 MAGs analyzed here were generated and deposited by the data producers ({DATA}) and are available from NCBI BioProject PRJNA1231077 and Zenodo (https://doi.org/10.5281/zenodo.15309541); the SRA run and BioSample accessions of the underlying reads are listed per MAG in Table S2P. The Bakta, Panaroo, GTDB-Tk, and DRAM outputs, derived trait-module tables, and analysis scripts generated in this study are available at https://github.com/Soonlab/Upcycling and will be deposited at Zenodo (DOI on acceptance).")

# ================================================================ Table 1: sample origin column
man = rep(man, "Assembly size, GC content, contig count, and N50 for each MAG, together with the principal *ure*-containing contig,",
          "Sample origin (microcosm sample of the data producers), assembly size, GC content, contig count, and N50 for each MAG, together with the principal *ure*-containing contig,")
ORIGIN = {"M1": "Manure (GT14SEXb)", "S13": "Manured soil (GT28BC2)", "S16": "Manured soil (GT28BC2)",
          "C22": "Manured soil (GT14BC2)", "S23": "Manured soil (GT2BC2)", "S26": "Manure (GT2SEX)"}
man = rep(man, "| MAG | Lineage | Size (Mb) |", "| MAG | Lineage | Origin (sample) | Size (Mb) |")
man = rep(man, "|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| **M1**", "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| **M1**")
for mag, o in ORIGIN.items():
    lin = "*Pseudomonas*\\_E" if mag in ("M1", "S26") else "*Sphingobacterium*"
    man = rep(man, f"| **{mag}** | {lin} | ", f"| **{mag}** | {lin} | {o} | ")

# ================================================================ sanity: nothing left of the old framing in the body
body = man.split("## References")[0]
for bad in ("swine", "sheep", "poultry", "MGnify", "7,599", "ACE hybrid", "livestock-slurry", "Livestock slurry", "livestock slurry",
            "PRJNA-XXXXXXX", "Fig. 5d", "Table S3K", "Table S3M", "Table S3G,H", "Table S3E,F", "waste source", "livestock source"):
    assert bad not in body, f"old framing survives: {bad!r}"
(HERE / "01_Manuscript.md").write_text(man, encoding="utf-8")

# ================================================================ legends
leg = rep(leg, "# Figure and Table Legends (ported from the authors' revised manuscript of 2026-09-17; port 2026-09-23)\n\nFigures are the 2026-09-09 pages in `Figures/`; the supplementary workbooks follow the S1A/S2A/S3A sheet scheme of the revised text.",
          "# Figure and Table Legends (SUBMISSION_v4, reframed 2026-09-23 for the true data provenance)\n\nFigures are the 2026-09-09 pages in `Figures/` except Fig 5, Fig S5 and the graphical abstract, rebuilt 2026-09-23 (`../new_figure/build_v4_*.py`); the supplementary workbooks follow the v4 sheet scheme (Table S3 re-lettered S3A–S3J).")
leg = rep(leg, "### Figure 1 | Phylogenomic distribution of MICP-associated genes across 111 livestock-waste MAGs.",
          "### Figure 1 | Phylogenomic distribution of MICP-associated genes across 111 cattle manure–soil microcosm MAGs.")
leg = rep(leg, "### Figure 5 | Species novelty, external prevalence, secondary-metabolite profiles, and pan-genome structure of the MAG panel.",
          "### Figure 5 | Species novelty, secondary-metabolite profiles, and pan-genome structure of the MAG panel.")
leg = rep(leg, " **(B)** Prevalence of MICP-associated genomic features across four MGnify livestock-microbiome catalogs and in the pooled dataset. Dark green bars indicate species clusters carrying *ureA*, *ureB*, and *ureC* together with at least one carbonic-anhydrase domain, and light green bars indicate species clusters in which *ureC* and carbonic anhydrase occurred on the same contig. Percentages are shown above the bars, and catalog sizes are indicated below. **(C)** Mean numbers of antiSMASH 7",
          " **(B)** Mean numbers of antiSMASH 7")
leg = rep(leg, "**(D)** Principal coordinates analysis of Panaroo gene presence/absence profiles based on Jaccard distance. Points are colored by livestock source, and the six prioritized candidates are highlighted with open coral circles and labels. Axis labels indicate the variance explained, and PERMANOVA results for source and genus are shown in the panel.",
          "**(C)** Principal coordinates analysis of Panaroo gene presence/absence profiles based on Jaccard distance. Points are colored by lineage group (*Sphingobacterium*, *Pseudomonas*\\_E, or other genera), and the six prioritized candidates are highlighted with open coral circles and labels. Axis labels indicate the variance explained, and the PERMANOVA result for genus is shown in the panel.")
leg = rep(leg, "### Figure S2 | DRAM metabolic context and CAZyme profiles of the livestock-waste MAG panel.",
          "### Figure S2 | DRAM metabolic context and CAZyme profiles of the MAG panel.")
leg = rep(leg, "### Figure S5 | Predicted growth rate, coverage-based abundance proxy, and codon-usage features of the MAG panel.",
          "### Figure S5 | Predicted growth rate, read-mapping coverage, and codon-usage features of the MAG panel.")
leg = rep(leg, "**(B)** Length-weighted SPAdes contig coverage for the six prioritized candidates and the remaining 105 MAGs. Coverage is shown on a logarithmic scale, with the two-sided Mann–Whitney U *P* value indicated. **(C)** Length-weighted contig coverage stratified by livestock source. Individual prioritized candidates are highlighted with open circles within their respective source groups. **(D)** Genome-wide GC content at the third codon position (GC3) in the six prioritized candidates and the remaining MAGs. **(E)** Effective number of codons (ENC), shown using the same group comparison. *P* values in panels D and E indicate two-sided Mann–Whitney U tests.",
          "**(B)** Read-mapping genome coverage of each MAG in its sample of origin, as deposited with the dataset (CoverM; Table S2P), for the six prioritized candidates and the remaining 105 MAGs. Coverage is shown on a logarithmic scale, with the two-sided Mann–Whitney U *P* value indicated. **(C)** Genome-wide GC content at the third codon position (GC3) in the six prioritized candidates and the remaining MAGs. **(D)** Effective number of codons (ENC), shown using the same group comparison. *P* values in panels C and D indicate two-sided Mann–Whitney U tests.")
leg = rep(leg, "Assembly size, GC content, contig count, and N50 for each MAG, together with the principal *ure*-containing contig,",
          "Sample origin (microcosm sample of the data producers), assembly size, GC content, contig count, and N50 for each MAG, together with the principal *ure*-containing contig,")
leg = rep(leg, "codon-usage metrics (S2O), coverage-based abundance estimates (S2P), antiSMASH BGC profiles (S2Q), DRAM annotation summaries (S2R–S2S), and pan-genome PCoA coordinates (S2T).",
          "codon-usage metrics (S2O), sample provenance with read-mapping coverage and NCBI accessions from the deposited dataset (S2P), antiSMASH BGC profiles (S2Q), DRAM annotation summaries (S2R–S2S), and pan-genome PCoA coordinates (S2T).")
leg = rep(leg, "Excel workbook containing 13 data sheets and a README. Analyses include permutation tests for functional traits (S3A), dbCAN class enrichment (S3B), global and pairwise PERMANOVA (S3C–S3D), *Pseudomonas*\\_E prevalence and contig-level screens (S3E–S3F), MGnify catalog summaries and per-cluster profiles (S3G–S3H), anti-phage defense comparisons (S3I), codeml M0 and yn00 selection analyses (S3J–S3K), coverage-based abundance comparisons by livestock source (S3L), and antiSMASH group comparisons (S3M).",
          "Excel workbook containing 10 data sheets and a README. Analyses include permutation tests for functional traits (S3A), dbCAN class enrichment (S3B), pan-genome PERMANOVA by genus (S3C), *Pseudomonas*\\_E prevalence and contig-level screens (S3D–S3E), anti-phage defense comparisons (S3F), codeml M0 and yn00 selection analyses (S3G–S3H), antiSMASH group comparisons (S3I), and the read-mapping coverage comparison between the prioritized candidates and the remaining MAGs (S3J).")
for bad in ("livestock", "MGnify", "waste source", "swine", "sheep", "poultry"):
    assert bad not in leg, f"old framing survives in legends: {bad!r}"
(HERE / "02_Figure_legends.md").write_text(leg, encoding="utf-8")
print("reframed: 01_Manuscript.md, 02_Figure_legends.md")
